[package]
name = "datadown"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "CLI for Markdown â†’ JSON/YAML/TOML/XML"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
datadown-core = { path = "../datadown-core", features = ["yaml", "toml", "xml"] }
